##### Week 15, 16:

## Feature Selection

Feature Selection is the process of selecting important features (columns) from a dataset and removing irrelevant or unnecessary features.  
We keep only those columns that are useful for the machine learning model and remove the rest.

Feature Selection म्हणजे dataset मधील important features (columns) निवडणे आणि irrelevant / unnecessary features काढून टाकणे.  
Dataset मधून जे columns model साठी उपयोगी आहेत ते ठेवणे आणि बाकीचे remove करणे.

#### Why is Feature Selection Important?

It improves model performance   
It reduces training time   
It helps reduce overfitting  
It makes the model simple and efficient  
The model becomes faster and more accurate.

##### Example:

Student Dataset:  
Name ❌  
Roll No ❌  
Marks ✅  
Study Hours ✅  

👉 Here:  

Marks and Study Hours are useful  
Name and Roll No are not useful

So, we use only the important features for building the model.

#### Types of Feature Selection

1️⃣ Filter Method  
2️⃣ Wrapper Method  
3️⃣ Embedded Method  

#### 1️⃣ Filter Method :

Filter Method is a feature selection technique where we select features using statistical measures, without using any machine learning model.  
Statistical techniques वापरून features select करतो  
Model वापरत नाही  
Data मधील features चा relation check करून selection करतो.

##### Techniques:

1️⃣ Correlation :  

Numeric data साठी वापरतो  
High correlation = important feature

2️⃣ Chi-Square Test :  

Categorical data साठी वापरतो

3️⃣ ANOVA (Analysis of Variance) : 
 
Feature आणि target मधील difference check करतो

##### Example:

जर दोन features same information देत असतील 👉 एक remove करतो

✅ Advantages:  
Fast   
Simple

❌ Disadvantages:  
Model performance consider करत नाही

In [1]:
import pandas as pd

data = {
    'Age': [20, 21, 22, 23, 24],
    'Marks': [60, 65, 70, 75, 80],
    'StudyHours': [2, 3, 4, 5, 6],
    'Random': [10, 5, 3, 8, 2]
}

df = pd.DataFrame(data)

# correlation
corr = df.corr()

# select important features
selected = corr['Marks'][corr['Marks'] > 0.5].index
print(selected)

Index(['Age', 'Marks', 'StudyHours'], dtype='object')


#### 2️⃣ Wrapper Method

Wrapper Method is a feature selection technique where we use a machine learning model to evaluate and select the best combination of features.  
Machine Learning model वापरून features select करतो  
Model run करून best feature combination शोधतो.

##### Techniques:

1️⃣ Forward Selection:

Start with no features  
Add features one by one  
Keep the features that improve performance

2️⃣ Backward Elimination:

Start with all features  
Remove one feature at a time  
Remove the least important features

3️⃣ Recursive Feature Elimination (RFE):

Train the model  
Remove the least important feature  
Repeat the process until the desired number of features is selected 

##### Example:

Dataset:

Age  
Study Hours  
Random  
Marks  

👉 Try combinations:

Age + Study Hours → Good performance  
Age + Random → Poor performance

👉 So, select Study Hours and remove Random

Step by step features add/remove करून best result मिळवतो

✅ Advantages:  
More accurate

❌ Disadvantages:  
Slow   
Computationally expensive

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
import pandas as pd

data = {
    'Age': [20, 21, 22, 23, 24],
    'StudyHours': [2, 3, 4, 5, 6],
    'Random': [10, 5, 3, 8, 2],
    'Marks': [60, 65, 70, 75, 80]
}

df = pd.DataFrame(data)

X = df[['Age', 'StudyHours', 'Random']]
y = df['Marks']

model = LinearRegression()

rfe = RFE(model, n_features_to_select=2)
fit = rfe.fit(X, y)

print("Selected Features:", X.columns[fit.support_])

Selected Features: Index(['Age', 'StudyHours'], dtype='object')


#### 3️⃣ Embedded Method :

The Embedded Method is a feature selection technique where feature selection happens automatically during the model training process.  
Feature selection model training दरम्यानच होते  
Model स्वतः training करताना important features select करतो.

##### Techniques:  

1️⃣ Lasso Regression (L1 Regularization):

Reduces some feature coefficients to zero  
Features with zero importance are removed

2️⃣ Decision Tree:

Automatically selects important features based on splits

3️⃣ Random Forest:

Provides feature importance scores

##### Example:

Dataset:

Age  
Study Hours  
Random  
Marks

👉 Model training:

Age → important  
Study Hours → important  
Random → not important (ignored)

👉 So, the model automatically selects useful features.

Decision Tree automatically important features निवडतो

✅ Advantages:  
Fast + Accurate 
Balanced method

❌ Disadvantages:  
Specific models वर depend असतो

In [3]:
from sklearn.linear_model import Lasso
import pandas as pd

data = {
    'Age': [20, 21, 22, 23, 24],
    'StudyHours': [2, 3, 4, 5, 6],
    'Random': [10, 5, 3, 8, 2],
    'Marks': [60, 65, 70, 75, 80]
}

df = pd.DataFrame(data)

X = df[['Age', 'StudyHours', 'Random']]
y = df['Marks']

model = Lasso(alpha=0.1)
model.fit(X, y)

print("Feature Coefficients:", model.coef_)

Feature Coefficients: [ 4.9432442   0.         -0.00526162]


If a coefficient is 0, that feature is not important.

##



## Feature Extraction :

Feature Extraction is the process of creating new features from raw data to make it more useful for a machine learning model

Feature Extraction म्हणजे raw data मधून नवीन useful features तयार करणे.

#### Key Idea :

Raw data → Process → New features  
Important information extract करतो

#### Examples :

- Image Data

Image → pixels → edges, shapes

👉 Model ला समजण्यासाठी features बनवतो

- Student Data

Marks, Attendance → combine करून performance score तयार करतो

### 1️⃣ PCA (Principal Component Analysis)

PCA is a technique used to reduce the number of features (dimensions) while keeping the most important information.

PCA म्हणजे dataset मधील features कमी करणे पण important information जपून ठेवणे.  
Dimensionality reduction technique    
जास्त features कमी करून important information ठेवतो

#### Key Idea:

Original features → new features (called principal components)  
Maximum variance (information) जपतो

#### Use:

When dataset has many features

#### Example:

Suppose:

Features: Height, Weight

👉 PCA → combine करून एक new feature तयार करतो (overall body size)

In [ ]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

# Load dataset
data = load_iris()
X = data.data

# Apply PCA (reduce to 3 features)
pca = PCA(n_components=3)
X_new = pca.fit_transform(X)

print(X_new)

[[-2.68412563  0.31939725 -0.02791483]
 [-2.71414169 -0.17700123 -0.21046427]
 [-2.88899057 -0.14494943  0.01790026]
 [-2.74534286 -0.31829898  0.03155937]
 [-2.72871654  0.32675451  0.09007924]
 [-2.28085963  0.74133045  0.16867766]
 [-2.82053775 -0.08946138  0.25789216]
 [-2.62614497  0.16338496 -0.02187932]
 [-2.88638273 -0.57831175  0.02075957]
 [-2.6727558  -0.11377425 -0.19763272]
 [-2.50694709  0.6450689  -0.07531801]
 [-2.61275523  0.01472994  0.10215026]
 [-2.78610927 -0.235112   -0.20684443]
 [-3.22380374 -0.51139459  0.06129967]
 [-2.64475039  1.17876464 -0.15162752]
 [-2.38603903  1.33806233  0.2777769 ]
 [-2.62352788  0.81067951  0.13818323]
 [-2.64829671  0.31184914  0.02666832]
 [-2.19982032  0.87283904 -0.12030552]
 [-2.5879864   0.51356031  0.21366517]
 [-2.31025622  0.39134594 -0.23944404]
 [-2.54370523  0.43299606  0.20845723]
 [-3.21593942  0.13346807  0.29239675]
 [-2.30273318  0.09870885  0.03912326]
 [-2.35575405 -0.03728186  0.12502108]
 [-2.50666891 -0.14601688

### 2️⃣ LDA (Linear Discriminant Analysis)

LDA is a technique used to separate different classes clearly.

LDA म्हणजे different classes (groups) वेगळे दाखवण्यासाठी feature तयार करणे.  
Used for classification problems  
Different classes (groups) clearly separate करण्यासाठी use करतो

#### Key Idea:

Class separation maximize करतो
Within-class difference कमी करतो

Same class मधील data जवळ आणतो आणि different class दूर ठेवतो

#### Use:

Face recognition, classification tasks

#### Example:

Students:

Pass / Fail

👉 LDA असा feature तयार करतो ज्यामुळे दोन्ही groups clearly वेगळे दिसतात

In [2]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.datasets import load_iris

# Load dataset
data = load_iris()
X = data.data
y = data.target

# Apply LDA
lda = LinearDiscriminantAnalysis(n_components=2)
X_new = lda.fit_transform(X, y)

print(X_new)

[[ 8.06179978e+00 -3.00420621e-01]
 [ 7.12868772e+00  7.86660426e-01]
 [ 7.48982797e+00  2.65384488e-01]
 [ 6.81320057e+00  6.70631068e-01]
 [ 8.13230933e+00 -5.14462530e-01]
 [ 7.70194674e+00 -1.46172097e+00]
 [ 7.21261762e+00 -3.55836209e-01]
 [ 7.60529355e+00  1.16338380e-02]
 [ 6.56055159e+00  1.01516362e+00]
 [ 7.34305989e+00  9.47319209e-01]
 [ 8.39738652e+00 -6.47363392e-01]
 [ 7.21929685e+00  1.09646389e-01]
 [ 7.32679599e+00  1.07298943e+00]
 [ 7.57247066e+00  8.05464137e-01]
 [ 9.84984300e+00 -1.58593698e+00]
 [ 9.15823890e+00 -2.73759647e+00]
 [ 8.58243141e+00 -1.83448945e+00]
 [ 7.78075375e+00 -5.84339407e-01]
 [ 8.07835876e+00 -9.68580703e-01]
 [ 8.02097451e+00 -1.14050366e+00]
 [ 7.49680227e+00  1.88377220e-01]
 [ 7.58648117e+00 -1.20797032e+00]
 [ 8.68104293e+00 -8.77590154e-01]
 [ 6.25140358e+00 -4.39696367e-01]
 [ 6.55893336e+00  3.89222752e-01]
 [ 6.77138315e+00  9.70634453e-01]
 [ 6.82308032e+00 -4.63011612e-01]
 [ 7.92461638e+00 -2.09638715e-01]
 [ 7.99129024e+00 -8

### 3️⃣ TF-IDF (Text Feature Extraction)

Important words ओळखतो text मध्ये

Text data मधील important words काढतो

#### Example:

Sentence:

“I love AI and AI is future”

👉 TF:  
AI = 2 times

👉 IDF:  
“AI” rare असेल → more important

👉 Final → “AI” important word

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample text
documents = [
    "I love AI",
    "AI is the future",
    "I love machine learning"
]

# Apply TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0.70710678 0.         0.         0.         0.70710678 0.
  0.        ]
 [0.40204024 0.52863461 0.52863461 0.         0.         0.
  0.52863461]
 [0.         0.         0.         0.62276601 0.4736296  0.62276601
  0.        ]]
['ai' 'future' 'is' 'learning' 'love' 'machine' 'the']


#

#

## Hyperparameter Tuning

Hyperparameter Tuning is the process of selecting the best values for model parameters to improve performance.

Hyperparameter Tuning म्हणजे machine learning model चे settings (parameters) best values ला set करणे, जेणेकरून model ची performance improve होईल.  
Model training आधी आपण जे parameters manually set करतो, त्यांना hyperparameters म्हणतात आणि त्यांना best value देण्याची process म्हणजे hyperparameter tuning.

Model training सुरू होण्यापूर्वी जे hyperparameters आपण सेट करतो, त्यांचे best values शोधणे म्हणजे Hyperparameter Tuning

#### Why it is Important?

Default values always best नसतात ❌  
Wrong values → poor accuracy  
Correct tuning → better accuracy + less overfitting  

Proper tuning केल्याने model जास्त accurate आणि stable होतो

#### Key Idea:

- Try different values  
- Train the model  
- Select the value that gives the best result  

We test different values and choose the one that produces the best output.

#### Example:

In a KNN model:

K = 1 → low accuracy  
K = 3 → better  
K = 5 → best  

👉 So, we select K = 5 as it gives the best performance.

### Methods of Hyperparameter Tuning:

#### 1️⃣ Grid Search :

Grid Search tries all possible combinations of hyperparameter values.

सगळ्या possible values combinations check करतो

#### Example:

K = 1, 3, 5  
Depth = 2, 4

Combinations:

(1,2), (1,4), (3,2), (3,4), (5,2), (5,4)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

# Load dataset
data = load_iris()
X, y = data.data, data.target

# Model
model = KNeighborsClassifier()

# Hyperparameters
param_grid = {
    'n_neighbors': [1, 3, 5, 7],
    'weights': ['uniform', 'distance']
}

# Grid Search
grid = GridSearchCV(model, param_grid, cv=5) # 5-fold cross-validation
grid.fit(X, y)

print("Best Parameters:", grid.best_params_)

Best Parameters: {'n_neighbors': 7, 'weights': 'uniform'}


#### 2️⃣ Random Search :

Random Search tries random combinations of hyperparameters instead of all.

Random values निवडून test करतो

#### Example:

Randomly tries:

(1,2), (5,4), (3,2)

In [7]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
import numpy as np

data = load_iris()
X, y = data.data, data.target

model = KNeighborsClassifier()

param_dist = {
    'n_neighbors': np.arange(1, 10),
    'weights': ['uniform', 'distance']
}

random = RandomizedSearchCV(model, param_dist, n_iter=5, cv=5) # 5 iterations - 5 random combinations, 5-fold cross-validation
random.fit(X, y)

print("Best Parameters:", random.best_params_)

Best Parameters: {'weights': 'distance', 'n_neighbors': np.int64(6)}


#### 3️⃣ Bayesian Optimization :

This method uses previous results to choose the next best set of hyperparameters.

आधीच्या results वरून पुढची best value निवडतो

In [ ]:
from skopt import BayesSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

data = load_iris()
X, y = data.data, data.target

model = KNeighborsClassifier()

param_space = {
    'n_neighbors': (1, 10),
    'weights': ['uniform', 'distance']
}

bayes = BayesSearchCV(model, param_space, n_iter=10, cv=5) # n_iter=10 - 10 iterations of Bayesian optimization, cv=5 - 5-fold cross-validation
bayes.fit(X, y)

print("Best Parameters:", bayes.best_params_)

Best Parameters: OrderedDict({'n_neighbors': 7, 'weights': 'distance'})


#### 4️⃣ Manual Search (Trial & Error) :

Manually values change करून best result शोधतो

स्वतः values बदलून try करतो

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

data = load_iris()
X, y = data.data, data.target

for k in [1, 3, 5, 7]:
    model = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(model, X, y, cv=5) # 5-fold cross-validation
    print(f"K={k}, Accuracy={scores.mean()}") # Average accuracy across 5 folds

K=1, Accuracy=0.96
K=3, Accuracy=0.9666666666666668
K=5, Accuracy=0.9733333333333334
K=7, Accuracy=0.9800000000000001
