Week 4: 

### numpy:-

"""NumPy (Numerical Python) is a library used for numerical calculations and working with arrays."""

NumPy is a Python library used for working with arrays.  
It also has functions for working in domain of linear algebra, fourier transform, and matrices.  
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.  
NumPy stands for Numerical Python.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.  
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

Create numpy ndarray object

- create 1-D array

numpy is used to work with arrays.  
the array object in NumPy is call ndarray.

In [4]:
import numpy as np
arr = np.array ([1,2,3,4,5])
print (arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- create 2-D array

An array that has 1-D arrays as its elements is called a 2-D array.  
These are often used to represent matrix or 2nd order tensors.

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

- 3-D array

An array that has 2-D arrays (matrices) as its elements is called 3-D array.  
These are often used to represent a 3rd order tensor.

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


- Higher Dimensional Arrays


An array can have any number of dimensions.  
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [11]:
import numpy as np

a= np.array(42)
b= np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)   #..........Get the number of dimensions of the following array
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Different Ways of Creating Numpy Array:-

1. numpy.array():  
Numpy array object in Numpy is called ndarray. We can create ndarray using this function.


Syntax: numpy.array(parameter)

In [ ]:
import numpy as np

arr = np.array([3,4,5,5])

print("Array :",arr)

2. numpy.fromiter():  
The fromiter() function create a new one-dimensional array from an iterable object.


Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [35]:
## ha function konatya pan iterable object pasun 1-D numpy arry create karato
#(String , List, Tuple, Generator)

import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype ='U2')

print("fromiter() array :",arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


3. numpy.arange():  
This is an inbuilt NumPy function that returns evenly spaced values within a given interval.


Syntax:  numpy.arange( start , stop, step , dtype=None )

In [13]:
import numpy as np

np.arange(1, 200 , 2, 
          dtype = np.float32)

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,
        23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,
        45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,
        67.,  69.,  71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,
        89.,  91.,  93.,  95.,  97.,  99., 101., 103., 105., 107., 109.,
       111., 113., 115., 117., 119., 121., 123., 125., 127., 129., 131.,
       133., 135., 137., 139., 141., 143., 145., 147., 149., 151., 153.,
       155., 157., 159., 161., 163., 165., 167., 169., 171., 173., 175.,
       177., 179., 181., 183., 185., 187., 189., 191., 193., 195., 197.,
       199.], dtype=float32)

4. numpy.linspace():  
This function returns evenly spaced numbers over a specified between two limits. 


Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [33]:
## 2 numbers madye equaly gap thevato 
## start value pasun stop value paryant equalgap asaleli numbers chi array milate

import numpy as np

np.linspace(3.5, 10, 3, True, 
            dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

- Orders meaning:-

'C' - c- style order (row wise)  
'F' - fortran- style order (column wise)  
'A' - Automatic (System decide)  
'K' - keep original order (jas ahe tas)

5. numpy.empty():  
This function create a new array of given shape and type without initializing value.  


Syntax: numpy.empty(shape, dtype=float, order='C')

In [ ]:
## np. empty() madhye order ha parameter array memory madhye kasa store hoil te decide karato.

import numpy as np

np.empty([4, 3], dtype = np.int32, order = 'f')

array([[4128860, 6619251, 6357096],
       [6029375, 7536754, 6619136],
       [3801155, 6946908,     114],
       [5570652, 6553697,  655360]], dtype=int32)

6. numpy.ones():  
This function is used to get a new array of given shape and type filled with ones (1).


Syntax: numpy.ones(shape, dtype=None, order='C')

In [20]:
import numpy as np

np.ones([4, 3], dtype = np.int32, order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

7. numpy.zeros():  
This function is used to get a new array of given shape and type filled with zeros (0). 


Syntax: numpy.zeros(shape, dtype=None)

In [22]:
import numpy as np
np.zeros([4, 3], dtype = np.int32, order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

### Access Array Elements:


Array indexing is the same as accessing an array element.  
You can access an array element by referring to its index number.

In [12]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[2])

1
3


In [ ]:
#..Get third and fourth elements from the following array and add them.

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


- Access 2-D Arrays:


To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [14]:
import numpy as np
arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [15]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


- Access 3-D Arrays:-


To access elements from 3-D arrays we can use comma separated  
integers representing the dimensions and the index of the element.

In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],)
print(arr[1, 1, 2])
print(arr)

12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


- Negative Indexing:- 


Use negative indexing to access an array from the end.

In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -3])

Last element from 2nd dim:  8


Shape of an Array:-


The shape of an array is the number of elements in each dimension.

In [3]:
import numpy as np

arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)   #..........Get the shape of the following array

(2, 4)


Data type objects (dtype):

 Data type objects (dtype) is an example of numpy.dtype class.  
 It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [ ]:
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

###  Slicing arrays: 

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
#.. Slice elements from index 1 to index 5 from the following array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

In [36]:
## Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
## Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

- Negative Slicing:


Use the minus operator to refer to an index from the end:

In [37]:
## Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


- Slicing 1-D array

In [ ]:
## Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])  #...1- starting , 5- Ending , 2- two cha gap sodun number print honar


[2 4]


In [43]:
## Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::3])

[1 4 7]


- Slicing 2-D array:

In [44]:
## From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [45]:
## From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [47]:
## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) #...[row start:row end, col start:col end]

[[2 3 4]
 [7 8 9]]
