Week 4: 

### numpy:-

"""NumPy (Numerical Python) is a library used for numerical calculations and working with arrays."""

NumPy is a Python library used for working with arrays.  
It also has functions for working in domain of linear algebra, fourier transform, and matrices.  
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.  
NumPy stands for Numerical Python.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.  
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

Create numpy ndarray object

- create 1-D array

numpy is used to work with arrays.  
the array object in NumPy is call ndarray.

In [4]:
import numpy as np
arr = np.array ([1,2,3,4,5])
print (arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- create 2-D array

An array that has 1-D arrays as its elements is called a 2-D array.  
These are often used to represent matrix or 2nd order tensors.

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

- 3-D array

An array that has 2-D arrays (matrices) as its elements is called 3-D array.  
These are often used to represent a 3rd order tensor.

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


- Higher Dimensional Arrays


An array can have any number of dimensions.  
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [11]:
import numpy as np

a= np.array(42)
b= np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)   #..........Get the number of dimensions of the following array
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Different Ways of Creating Numpy Array:-

1. numpy.array():  
Numpy array object in Numpy is called ndarray. We can create ndarray using this function.


Syntax: numpy.array(parameter)

In [ ]:
import numpy as np

arr = np.array([3,4,5,5])

print("Array :",arr)

2. numpy.fromiter():  
The fromiter() function create a new one-dimensional array from an iterable object.


Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [35]:
## ha function konatya pan iterable object pasun 1-D numpy arry create karato
#(String , List, Tuple, Generator)

import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype ='U2')

print("fromiter() array :",arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


3. numpy.arange():  
This is an inbuilt NumPy function that returns evenly spaced values within a given interval.


Syntax:  numpy.arange( start , stop, step , dtype=None )

In [13]:
import numpy as np

np.arange(1, 200 , 2, 
          dtype = np.float32)

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,
        23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,
        45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,
        67.,  69.,  71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,
        89.,  91.,  93.,  95.,  97.,  99., 101., 103., 105., 107., 109.,
       111., 113., 115., 117., 119., 121., 123., 125., 127., 129., 131.,
       133., 135., 137., 139., 141., 143., 145., 147., 149., 151., 153.,
       155., 157., 159., 161., 163., 165., 167., 169., 171., 173., 175.,
       177., 179., 181., 183., 185., 187., 189., 191., 193., 195., 197.,
       199.], dtype=float32)

4. numpy.linspace():  
This function returns evenly spaced numbers over a specified between two limits. 


Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [33]:
## 2 numbers madye equaly gap thevato 
## start value pasun stop value paryant equalgap asaleli numbers chi array milate

import numpy as np

np.linspace(3.5, 10, 3, True, 
            dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

- Orders meaning:-

'C' - c- style order (row wise)  
'F' - fortran- style order (column wise)  
'A' - Automatic (System decide)  
'K' - keep original order (jas ahe tas)

5. numpy.empty():  
This function create a new array of given shape and type without initializing value.  


Syntax: numpy.empty(shape, dtype=float, order='C')

In [ ]:
## np. empty() madhye order ha parameter array memory madhye kasa store hoil te decide karato.

import numpy as np

np.empty([4, 3], dtype = np.int32, order = 'f')

array([[4128860, 6619251, 6357096],
       [6029375, 7536754, 6619136],
       [3801155, 6946908,     114],
       [5570652, 6553697,  655360]], dtype=int32)

6. numpy.ones():  
This function is used to get a new array of given shape and type filled with ones (1).


Syntax: numpy.ones(shape, dtype=None, order='C')

In [20]:
import numpy as np

np.ones([4, 3], dtype = np.int32, order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

7. numpy.zeros():  
This function is used to get a new array of given shape and type filled with zeros (0). 


Syntax: numpy.zeros(shape, dtype=None)

In [22]:
import numpy as np
np.zeros([4, 3], dtype = np.int32, order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

### Access Array Elements:


Array indexing is the same as accessing an array element.  
You can access an array element by referring to its index number.

In [12]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[2])

1
3


In [ ]:
#..Get third and fourth elements from the following array and add them.

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


- Access 2-D Arrays:


To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [14]:
import numpy as np
arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [15]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


- Access 3-D Arrays:-


To access elements from 3-D arrays we can use comma separated  
integers representing the dimensions and the index of the element.

In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],)
print(arr[1, 1, 2])
print(arr)

12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


- Negative Indexing:- 


Use negative indexing to access an array from the end.

In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -3])

Last element from 2nd dim:  8


Data type objects (dtype):

 Data type objects (dtype) is an example of numpy.dtype class.  
 It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [ ]:
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

###  Slicing arrays: 

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
#.. Slice elements from index 1 to index 5 from the following array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

In [36]:
## Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
## Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

- Negative Slicing:


Use the minus operator to refer to an index from the end:

In [37]:
## Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


- Slicing 1-D array

In [ ]:
## Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])  #...1- starting , 5- Ending , 2- two cha gap sodun number print honar


[2 4]


In [43]:
## Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::3])

[1 4 7]


- Slicing 2-D array:

In [44]:
## From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [45]:
## From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [47]:
## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) #...[row start:row end, col start:col end]

[[2 3 4]
 [7 8 9]]


- Shape of an Array:-


The shape of an array is the number of elements in each dimension.

In [ ]:
import numpy as np

arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)   #..........Get the shape of the following array

- Reshaping arrays:


Reshaping means changing the shape of an array.  
The shape of an array is the number of elements in each dimension.  
By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape from 1-D to 2-D

In [ ]:
# Cconvert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape from 1-D to 3-D

In [3]:
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


- Flattening the arrays:


Flattening array means converting a multidimensional array into a 1D array.  
We can use reshape(-1) to do this.

In [1]:
## Convert the array into a 1D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


1. Copy

    A copy creates a new object with its own data.

    Key points :


    Stored in a different memory location  
    Changes in the copy do NOT affect the original  
    Safer, but uses more memory

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = a.copy()

b[0] = 100
print(a)  # [1 2 3]
print(b)  # [100 2 3]

[1 2 3]
[100   2   3]


2. View

    A view does not create new data.
    It just provides a different way to look at the same data.

    Key points

    Shares the same memory  
    Changes in the view DO affect the original  
    Faster and memory-efficient

In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = a.view()

b[0] = 100
print(a)  # [100 2 3]
print(b)  # [100 2 3]

[100   2   3]
[100   2   3]


- Check if Array Owns its Data:

    Every NumPy array has the attribute base that returns None if the array owns the data.  
    Otherwise, the base  attribute refers to the original object.

In [ ]:
## Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()  # returns none
y = arr.view()  # returns the original array

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### Iterating Arrays:-


Iterating means going through elements one by one.  
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

- 1-D Array: 

In [8]:
# Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


- 2-D Array:

In [9]:
# Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


- 3-D Array:

In [ ]:
# Iterate on the elements of the following 3-D array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

In [ ]:
# Iterate down to the scalars:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

- Iterating Arrays Using nditer():

    The function nditer() is a helping function that can be used from very basic to very advanced iterations.   

Iterating on Each Scalar Element 
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
# Iterate through the following 3-D array:

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Iterating Array With Different Data Types

Normally, NumPy array elements have fixed data type.  
But while iterating, we can temporarily change the datatype using op_dtypes.

👉 NumPy does NOT change the original array datatype.
So it uses extra memory, called buffer.

Why buffer?

Original array remains same  
Temporary space is used to convert datatype

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

"""
arr is integer array
op_dtypes=['S'] → elements are converted to string
buffered → temporary memory used
Original array does not change
"""

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


### Iterating With Different Step Size

Sometimes we don’t want all elements.  
We want to skip elements while iterating.


👉 This is done using slicing + iteration

In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):  
    print(x)
    
"""
: → all rows
::2 → every 2nd element (step size = 2)
Elements skipped in between
"""


1
3
5
7


'\n: → all rows\n::2 → every 2nd element (step size = 2)\nElements skipped in between\n'

### Enumerated Iteration Using ndenumerate()

Enumeration means:  
👉 Element + its index number

When we need:

    element value  
    corresponding index

In [17]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


### numpy joining array:-

Joining means putting contents of two or more arrays in a single array.  
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

| Axis     | Meaning | Direction    | Result        |
| -------- | ------- | ------------ | ------------- |
| `axis=0` | Rows    | Vertical ↓   | Stack rows    |
| `axis=1` | Columns | Horizontal → | Stack columns |


In [1]:
## Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [7]:
## Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions:-
 
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis.  
If axis is not explicitly passed it is taken as 0.

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


- Stacking Along Rows:


NumPy provides a helper function: hstack() to stack along rows.

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


- Stacking Along Columns:


NumPy provides a helper function: vstack()  to stack along columns.

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


- Stacking Along Height (depth):-


NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Split Array:-

- Splitting NumPy Arrays:-


Splitting is reverse operation of Joining.  
Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [14]:
## Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


- Split Into Arrays:
The return value of the array_split() method is a list containing each of the split as an array.

In [15]:
## Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


- Splitting 2-D Arrays:

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [16]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [17]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


### Searching Arrays:-

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [19]:
## Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [20]:
## Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [21]:
## Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)


2


### Sorting Arrays:
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [22]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [23]:
## Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [25]:
## Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


- Sorting 2-D Array:

In [27]:
## Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filter Array:

Getting some elements out of an existing array and creating a new array out of them is called filtering.  
In NumPy, you filter an array using a boolean index list.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [28]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]
